--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: cid; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cid
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.cid OWNER TO postgres;

--
-- Name: SEQUENCE cid; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE public.cid IS 'config 自增主键';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.config (
    cid bigint DEFAULT nextval('public.cid'::regclass) NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    id integer NOT NULL,
    os text,
    lang text,
    rule_id text,
    data text[],
    type integer,
    param text[]
);


ALTER TABLE public.config OWNER TO postgres;

--
-- Name: COLUMN config.cid; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.config.cid IS '主键，自增';


--
-- Name: COLUMN config."timestamp"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.config."timestamp" IS '时间戳，标记存储的时间';


--
-- Name: COLUMN config.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.config.id IS '配置文件 ID，方便读取';


--
-- Name: COLUMN config.os; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.config.os IS '标记分发的系统';


--
-- Name: COLUMN config.lang; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.config.lang IS '标记系统语言';


--
-- Name: COLUMN config.rule_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.config.rule_id IS '检查项 ID';


--
-- Name: COLUMN config.data; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.config.data IS '检查预期值';


--
-- Name: COLUMN config.type; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.config.type IS '比对类型（0直接比对，1需要进行文本处理）';


--
-- Name: COLUMN config.param; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.config.param IS '字符数组类型，存储多个命令行或 path';


--
-- Name: result; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.result (
    rid bigint NOT NULL,
    "timestamp" time without time zone NOT NULL,
    utc text NOT NULL,
    id integer NOT NULL,
    os text,
    lang text,
    server_ip inet,
    host_ip inet,
    rule_id text,
    expected text[],
    actual text[],
    status text
);


ALTER TABLE public.result OWNER TO postgres;

--
-- Name: COLUMN result.rid; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.result.rid IS '主键，自增';


--
-- Name: COLUMN result."timestamp"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.result."timestamp" IS '时间戳，标记采集的时间（统一）';


--
-- Name: COLUMN result.utc; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.result.utc IS '标记UTC偏移量，如+2';


--
-- Name: COLUMN result.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.result.id IS '配置文件 ID，方便读取';


--
-- Name: COLUMN result.os; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.result.os IS '标记系统类型';


--
-- Name: COLUMN result.lang; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.result.lang IS '标记系统语言';


--
-- Name: COLUMN result.server_ip; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.result.server_ip IS '标记负责比对的主机';


--
-- Name: COLUMN result.host_ip; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.result.host_ip IS '标记被比对的主机';


--
-- Name: COLUMN result.rule_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.result.rule_id IS '标记是哪个检查项';


--
-- Name: COLUMN result.expected; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.result.expected IS '查询结果的预期值';


--
-- Name: COLUMN result.actual; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.result.actual IS '查询结果的实际值';


--
-- Name: COLUMN result.status; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.result.status IS '比对的结果（pass/failed）';


--
-- Name: result_rid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.result ALTER COLUMN rid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.result_rid_seq
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0
    NO MAXVALUE
    CACHE 1
);


--
-- Name: statistics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.statistics (
    sid bigint NOT NULL,
    check_time timestamp without time zone NOT NULL,
    utc text NOT NULL,
    host_ip inet,
    failed_list text[],
    pass_list text[]
);


ALTER TABLE public.statistics OWNER TO postgres;

--
-- Name: COLUMN statistics.sid; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics.sid IS '主键，自增';


--
-- Name: COLUMN statistics.check_time; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics.check_time IS '机器采集时间，采用标准国际时间';


--
-- Name: COLUMN statistics.utc; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics.utc IS '标记UTC偏移量，如+2';


--
-- Name: COLUMN statistics.host_ip; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics.host_ip IS '检查的机器ip';


--
-- Name: COLUMN statistics.failed_list; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics.failed_list IS '失败的检查项列表（存放ruleID）';


--
-- Name: COLUMN statistics.pass_list; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics.pass_list IS '成功的检查项列表（存放ruleID）';


--
-- Name: statistics_sid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.statistics ALTER COLUMN sid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.statistics_sid_seq
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: config; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.config (cid, "timestamp", id, os, lang, rule_id, data, type, param) FROM stdin;
1	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1961	{1,1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\NetworkProvider\\\\\\\\HardenedPaths:RequireIntegrity","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\NetworkProvider\\\\\\\\HardenedPaths:RequireMutualAuthentication"}
2	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0956	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\Network Connections:NC_AllowNetBridge_NLA"}
3	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0375	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Microsoft\\\\\\\\wcmsvc\\\\\\\\wifinetworkmanager\\\\\\\\config:AutoConnectAllowedOEM"}
4	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0522	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\LanmanWorkstation:AllowInsecureGuestAuth"}
5	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0656	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\DNSClient:EnableMulticast"}
6	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0631	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Policies\\\\\\\\System\\\\\\\\Audit:ProcessCreationincludeCmdLine_Enabled"}
7	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0001	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\System:BlockDomainPicturePassword"}
8	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0236	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\System:AllowDomainPINLogon"}
9	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0116	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Power\\\\\\\\PowerSettings\\\\\\\\0e796bdb_100d_47d6_a2d5_f7d2daa51f51:DCSettingIndex"}
10	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0066	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Power\\\\\\\\PowerSettings\\\\\\\\0e796bdb_100d_47d6_a2d5_f7d2daa51f51:ACSettingIndex"}
11	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7520	{127}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\PassportForWork\\\\\\\\PINComplexity:MaximumPINLength"}
12	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7521	{8}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\PassportForWork\\\\\\\\PINComplexity:MinimumPINLength"}
13	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0284	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\W32time\\\\\\\\TimeProviders\\\\\\\\NtpClient:Enabled"}
14	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0621	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:CreateEncryptedOnlyTickets"}
15	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0691	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:LoggingEnabled"}
16	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0931	{1,1,0,1,1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:fAllowToGetHelp","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:fAllowFullControl","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:MaxTickertExpiry","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:MaxTickertExpiryUnits","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:fUseMailto"}
17	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0866	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Policies\\\\\\\\System\\\\\\\\CredSSP\\\\\\\\Parameters:AllowEncryptionOracle"}
18	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0759	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\AdvertisingInfo:DisabledByGroupPolicy"}
19	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1581	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\SQMClient\\\\\\\\Windows:CEIPEnable"}
20	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1231	{2}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Messenger\\\\\\\\Client:CEIP"}
21	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1196	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\Windows Error Reporting:Disabled"}
22	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0166	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\TabletPC:PreventHandwritingDataSharing"}
23	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0761	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\HandwritingErrorReports:PreventHandwritingErrorReports"}
24	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0391	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\InputPersonalization:AllowInputPersonalization"}
25	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1381	{1}	0	{"User\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\WindowsMediaPlayer:EnableScreenSaver"}
26	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1211	{1}	0	{"User\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\WindowsMediaPlayer:PreventCDDVDMetadataRetrieval"}
27	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1601	{1}	0	{"User\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\WindowsMediaPlayer:PreventCodecDownload"}
28	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1866	{1}	0	{"User\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\WindowsMediaPlayer:PreventMusicFileMetadataRetrieval"}
29	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0186	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\PreviewBuilds:AllowBuildPreview"}
30	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0602	{4}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\WindowsUpdate\\\\\\\\AU:AUOptions"}
31	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0721	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\WindowsUpdate:ManagePreviewBuilds"}
32	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1011	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\Explorer:NoAutoplayfornonVolume"}
33	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1041	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Policies\\\\\\\\Explorer:NoAutorun"}
34	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1891	{181}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Policies\\\\\\\\Explorer:NoDriveTypeAutoRun"}
35	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0556	{131072}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\EventLog\\\\\\\\Application:MaxSize"}
36	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0491	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\EventLog\\\\\\\\Application:Retention"}
37	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0671	{524288}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\EventLog\\\\\\\\Security:MaxSize"}
38	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0176	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\EventLog\\\\\\\\Security:Retention"}
39	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0681	{131072}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\EventLog\\\\\\\\System:MaxSize"}
40	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0651	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\EventLog\\\\\\\\System:Retention"}
41	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0376	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\EventLog\\\\\\\\Setup:Enabled"}
42	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0766	{131072}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\EventLog\\\\\\\\Setup:MaxSize"}
43	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0051	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\EventLog\\\\\\\\Setup:Retention"}
44	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0046	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\System:NolocalPasswordResetQuestions"}
45	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0277	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\MicrosoftAccount:DisableUserAuth"}
46	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0316	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Policies\\\\\\\\System:DisableAutomaticRestartSignOn"}
47	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1926	{0,1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\PassportForWork:DisablePostLogonProvisioning","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\PassportForWork:Enabled"}
48	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_8451	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\PassportForWork\\\\\\\\ExcludeSecurityDevices:TPM12"}
49	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_5551	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\WinBio\\\\\\\\Credential Provider:Domain Accounts"}
50	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_5557	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\PassportForWork:UserCertificateForOnPremAuth"}
51	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_9356	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\PassportForWork:EnablePinRecovery"}
52	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7642	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Biometrics\\\\\\\\FacialFeatures:EnhancedAntiSpoofing"}
53	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0739	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\HomeGroup:AllowInsecureGuestAuth"}
54	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0706	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:AuthenticationLevel"}
55	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0776	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:DisablePasswordSaving"}
56	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0836	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:fPromptForPassword"}
57	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0246	{2}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:SecurityLayer"}
58	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0511	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:UserAuthentication"}
59	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0666	{3}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:MinEncryptionLevel"}
60	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0156	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:fDenyTSConnections"}
61	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0911	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\WinRM\\\\\\\\Client:AllowBasic"}
62	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0841	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\WinRM\\\\\\\\Client:AllowUnencryptedTraffic"}
63	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0606	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\WinRM\\\\\\\\Service:AllowBasic"}
64	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0581	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\WinRM\\\\\\\\Service:AllowUnencryptedTraffic"}
65	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0736	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\GameDVR:AllowGameDVR"}
66	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0396	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:MorBehavior"}
67	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0331	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:DisableExternalDMAUnderLock"}
68	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0226	{1,"Siemens AG"}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:IdentificationField","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:IdentificationFieldString"}
69	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0971	{7,4,4}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:EncryptionMethodWithXtsFdv","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:EncryptionMethodWithXtsOs","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:EncryptionMethodWithXtsRdv"}
70	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1636	{0,0,0,0,0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:FDVActiveDirectoryBackup","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:FDVHideRecoveryPage","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:FDVManageDRA","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:FDVRecovery","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:FDVRequireActiveDirectoryBackup"}
71	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1871	{0,0,0,0,0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:OSActiveDirectoryBackup","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:OSHideRecoveryPage","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:OSManageDRA","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:OSRecovery","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:OSRequireActiveDirectoryBackup"}
72	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1116	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:FDVEncryptionType"}
73	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1826	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:OSEncryptionType"}
74	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1366	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:OSEnablePreBootPinExceptionOnDECapableDevice"}
75	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1466	{8}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:MinimumPIN"}
76	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1371	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:OSEnablePrebootInputProtectorsOnSlates"}
77	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1981	{1,1,2,2,2,2}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:UseAdvancedStartup","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:EnableBDEWithNoTPM","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:UseTPM","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:UseTPMPIN","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:UseTPMKey","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:UseTPMKeyPIN"}
78	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1206	{0,0,0,0,0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:RDVActiveDirectoryBackup","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:RDVHideRecoveryPage","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:RDVManageDRA","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:RDVRecovery","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:RDVRequireActiveDirectoryBackup"}
79	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1101	{1,0,2,8}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:RDVPassphrase","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:RDVEnforcePassphrase","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:RDVPassphraseComplexity","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:RDVPassphraseLength"}
80	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1671	{1,1,1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:RDVConfigureBDE","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:RDVAllowBDE","Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:RDVDisableBDE"}
81	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1201	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:RDVEncryptionType"}
82	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0756	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\AppPrivacy:LetAppsActivateWithVoice"}
83	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0341	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\AppPrivacy:LetAppsActivateWithVoiceAboveLock"}
84	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1791	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\LocationAndSensors:DisableLocation"}
85	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1226	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\LocationAndSensors:DisableLocationScripting"}
86	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0689	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\AppPrivacy:LetAppsAccessAccountInfo"}
87	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0968	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\AppPrivacy:LetAppsGetDiagnosticInfo"}
88	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1651	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\DataCollection:AllowTelemetry"}
89	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1446	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\DataCollection:DoNotShowFeedbackNotifications"}
90	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1856	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\DataCollection:DisableTelemetryOptInSettingsUx"}
91	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1236	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\DataCollection:DisableTelemetryOptInChangeNotificatification"}
92	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0353	{2}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\AppPrivacy:LetAppsSyncWithDevices"}
93	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1291	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\Windows Search:DisableWebSearch"}
94	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1096	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\Windows Search:ConnectedSearchUseWeb"}
95	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1736	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\Windows Error Reporting:Disabled"}
96	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0261	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Policies\\\\\\\\TextInput:AllowLinguisticDataCollection"}
97	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0372	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\AppPrivacy:LetAppsAccessBackgroundSpatialPerception"}
98	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1181	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\WindowsMediaPlayer:GroupPrivacyAcceptance"}
99	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1661	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\WindowsMediaPlayer:DisableAutoUpdate"}
100	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1306	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\WindowsMediaPlayer:PreventLibrarySharing"}
101	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1391	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\PushToInstall:DisablePushToInstall"}
102	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0564	{1}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CloudContent:DisableWindowsConsumerFeatures"}
103	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1841	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\Windows Search:AllowCortana"}
104	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1906	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\Windows Search:AllowCortanaAboveLock"}
105	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0526	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\System:PublishUserActivities"}
106	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0686	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\System:UploadUserActivities"}
107	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0796	{0}	0	{"Machine\\\\\\\\SOFTWARE\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\System:EnableMmx"}
108	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0711	{1,AllSigned}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\PowerShell:EnableScripts","Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\PowerShell:ExecutionPolicy"}
109	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0461	\N	0	{"Xbox Live 网络服务"}
110	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0946	\N	0	{"Xbox Live 游戏保存"}
111	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0416	\N	0	{"Xbox Live 身份验证管理器"}
112	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0506	\N	0	{"Xbox Accessory Management Service"}
113	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0521	\N	0	{"Remote Access Auto Connection Manager"}
114	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0961	\N	0	{"Microsoft iSCSI Initiator Service"}
115	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0846	\N	0	{LxssManager}
116	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0386	\N	0	{"Geolocation Service"}
117	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0056	\N	0	{"Downloaded Maps Manager"}
118	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0936	\N	0	{蓝牙音频网关服务}
119	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0636	\N	0	{蓝牙支持服务}
120	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0086	{1}	0	{"Machine\\\\\\\\System\\\\\\\\CurrentControlSet\\\\\\\\Control\\\\\\\\SCMConfig:EnableSvchostMitigationPolicy"}
121	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0655	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CloudContent:DisableSoftLanding"}
122	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1896	{1}	0	{"User\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CloudContent:DisableWindowsSpotlightOnSettings"}
123	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1251	{1}	0	{"User\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CloudContent:DisableWindowsSpotlightOnActionCenter"}
124	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1706	{1}	0	{"User\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CloudContent:DisableWindowsSpotlightWindowsWelcomeExperience"}
125	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1156	{1}	0	{"User\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CloudContent:DisableWindowsSpotlightFeatures"}
126	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1546	{1}	0	{"User\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CloudContent:DisableTailoredExperiencesWithDiagnosticData"}
127	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1711	{1}	0	{"User\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CloudContent:DisableThirdPartySuggestions"}
128	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1066	{2}	0	{"User\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CloudContent:ConfigureWindowsSpotlight"}
129	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0951	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\PushNotifications:NoCloudApplicationNotification"}
130	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0611	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\System:DisableLockScreenAppNotifications"}
131	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0303	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\Connect:AllowProjectionToPC"}
132	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1941	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\WCN\\\\\\\\UI:DisableWcnUi"}
133	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1036	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\WCN\\\\\\\\Registrars:DisableInBand802DOT11Registrar"}
134	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0181	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\System:EnableActivityFeed"}
135	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0441	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\SecondaryAuthenticationFactor:AllowSecondaryAuthenticationDevice"}
136	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0194	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\System:EnableCdp"}
137	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1831	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:RDVHardwareEncryption"}
138	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1416	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:OSHardwareEncryption"}
139	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1971	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\FVE:FDVHardwareEncryption"}
140	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0819	{1}	0	{"User\\\\\\\\Software\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Policies\\\\\\\\Explorer:NoRecycleFiles"}
141	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1341	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:fAllowUnsolicited"}
142	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1611	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows NT\\\\\\\\Terminal Services:fAllowToGetHelp"}
143	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1576	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CredentialsDelegation:AllowSavedCredentialsWhenNTLMOnly"}
144	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1596	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CredentialsDelegation:AllowSavedCredentials"}
145	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1491	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CredentialsDelegation:AllowSavedCredentials"}
146	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1696	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CredentialsDelegation:AllowFreshCredentialsWhenNTLMOnly"}
147	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1481	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CredentialsDelegation:AllowDefCredentialsWhenNTLMOnly"}
148	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1966	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CredentialsDelegation:AllowDefaultCredentials"}
149	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1526	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CredentialsDelegation:RestrictedRemoteAdministration"}
150	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1266	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CredentialsDelegation:AllowProtectedCreds"}
151	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1821	{1}	0	{"Machine\\\\\\\\System\\\\\\\\CurrentControlSet\\\\\\\\Policies\\\\\\\\EarlyLaunch:DriverLoadPolicy"}
152	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1026	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\OneDrive:DisableFileSync"}
153	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0701	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\PassportForWork:Enabled"}
154	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_6453	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Spynet:DisableBlockAtFirstSeen"}
155	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7345	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Remediation:Scan_ScheduleDay"}
156	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_4652	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Real_Time Protection:LocalSettingOverrideDisableOnAccessProtection"}
157	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_4653	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Real_Time Protection:LocalSettingOverrideRealtimeScanDirection"}
158	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_2096	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Real_Time Protection:LocalSettingOverrideDisableRealtimeMonitoring"}
159	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_2034	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Real_Time Protection:LocalSettingOverrideDisableBehaviorMonitoring"}
160	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_5871	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Signature Updates:UpdateOnStartUp"}
161	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_2754	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Signature Updates:DisableUpdateOnStartupWithoutEngine"}
162	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_6483	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Scan:DisablePackedExeScanning"}
163	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_6444	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Scan:DisableHeuristics"}
164	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_6476	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\NIS:DisableProtocolRecognition"}
165	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_5456	{2}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\MpEngine:MpCloudBlockLevel"}
166	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_3987	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Real_Time Protection:DisableScanOnRealtimeEnable"}
167	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_6489	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Real_Time Protection:DisableRawWriteNotification"}
168	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_3934	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Real_Time Protection:DisableOnAccessProtection"}
169	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_3958	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Real_Time Protection:RealtimeScanDirection"}
170	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_4876	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Real_Time Protection:LocalSettingOverrideDisableIOAVProtection"}
171	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_4754	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Spynet:LocalSettingOverrideSpynetReporting"}
172	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_3654	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Real_Time Protection:DisableRealtimeMonitoring"}
173	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_4537	{2}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender:PUAProtection"}
174	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0486	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender Security Center\\\\\\\\App and Browser protection:DisallowExploitProtectionOverride"}
175	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_1421	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\System:EnableSmartScreen"}
176	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0306	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\DriverInstall\\\\\\\\Restrictions:AllowUserDeviceClasses"}
177	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0136	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Windows Defender Exploit Guard\\\\\\\\Network Protection:EnableNetworkProtection"}
178	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0616	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Scan:CheckForSignaturesBeforeRunningScan"}
179	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0696	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Signature Updates:SignatureUpdateInterval"}
180	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0531	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Scan:DisableEmailScanning"}
181	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0426	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Scan:DisableRemovableDriveScanning"}
182	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0746	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Scan:DisableArchiveScanning"}
183	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0771	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Real_Time Protection:DisableBehaviorMonitoring"}
184	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0541	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Real_Time Protection:DisableIOAVProtection"}
185	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0076	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender\\\\\\\\Reporting:DisableGenericRePorts"}
186	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0981	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows Defender:DisableAntiSpyware"}
187	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7896	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\1:1800"}
188	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7931	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:1607"}
189	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7556	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:1804"}
190	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7966	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:160A"}
191	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7561	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:2708"}
192	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7961	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:2709"}
193	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7266	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:2104"}
194	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7276	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:1800"}
195	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7356	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:1406"}
196	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7776	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1806"}
197	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7016	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1607"}
198	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7701	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1804"}
199	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7971	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:160A"}
200	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7351	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2708"}
201	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7381	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2709"}
202	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7951	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2104"}
203	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7926	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1608"}
204	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7091	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1800"}
205	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7676	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1407"}
206	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7751	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2300"}
207	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7261	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1406"}
208	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7136	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer\\\\\\\\Feeds:AllowBasicAuthInClear"}
209	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7496	{65536}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:1A00"}
210	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7876	{196608}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1A00"}
211	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7206	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:2500"}
212	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7156	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2500"}
213	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7006	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:1A04"}
214	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7296	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:1609"}
215	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7986	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1601"}
216	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7316	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1601"}
217	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7916	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1609"}
218	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7271	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings:WarnOnBadCertRecving"}
219	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7196	{2688}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings:SecureProtocols"}
220	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7041	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:1809"}
221	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7151	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1809"}
222	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7921	{2,1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\SettingSync:DisableCredentialsSettingSync","Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\SettingSync:DisableCredentialsSettingSyncUserOverride"}
223	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7111	{2,1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\SettingSync:DisableWebBrowserSettingSync","Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\SettingSync:DisableWebBrowserSettingSyncUserOverride"}
224	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7636	{1}	0	{"User\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\IEAK:NoAutomaticSignup"}
225	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7471	{no}	0	{"User\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer\\\\\\\\Main:FormSuggest Passwords"}
226	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7161	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer\\\\\\\\Security:DisableSecuritySettingsCheck"}
227	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7461	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer\\\\\\\\PhishingFilter:EnabledV8"}
228	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7541	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer\\\\\\\\Main:DisableFirstRunCustomize"}
229	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7361	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer\\\\\\\\PhishingFilter:EnabledV9"}
230	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7231	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\2:2301"}
231	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7721	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\1:2301"}
232	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7086	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:2301"}
233	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7906	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2301"}
234	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7346	{yes}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer\\\\\\\\Main:NoReportSiteProblems"}
235	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7956	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer\\\\\\\\Suggested Sites:Enabled"}
236	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7871	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer\\\\\\\\Restrictions:NoCrashDetection"}
237	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7126	{2}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer\\\\\\\\Recovery:AutoRecover"}
238	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7191	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer\\\\\\\\SQM:DisableCustomerImprovementProgram"}
239	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7596	{1}	0	{"User\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer\\\\\\\\Restrictions:NoHelpItemSendFeedback"}
240	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7121	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer:AllowServicePoweredQSA"}
241	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7726	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer\\\\\\\\FlipAhead:Enabled"}
242	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7766	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer\\\\\\\\Activities:NoActivities"}
243	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7426	{no}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Internet Explorer\\\\\\\\Main:Enable Browser Extensions"}
244	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7326	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\2:1409"}
245	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7526	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\1:1409"}
246	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7651	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:1409"}
247	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7616	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:2105"}
248	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7021	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:2103"}
249	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7631	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:2102"}
250	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7576	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:1206"}
251	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7976	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:1407"}
252	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7591	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:140C"}
253	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7806	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1409"}
254	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7731	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1402"}
255	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7571	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2105"}
256	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7771	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2103"}
257	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7981	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2102"}
258	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7051	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1206"}
259	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7831	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1407"}
260	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7816	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:140C"}
261	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7581	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1400"}
262	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7481	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:2200"}
263	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7536	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2200"}
264	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7586	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1604"}
265	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7146	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1803"}
266	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7641	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\2:120A"}
267	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7306	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\1:120A"}
268	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7501	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\1:1209"}
269	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7036	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:120A"}
270	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7681	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:1209"}
271	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7226	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:120A"}
272	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7566	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1209"}
273	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7301	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2000"}
274	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7366	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\2:270C"}
275	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7881	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\1:1201"}
276	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7371	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\1:1004"}
277	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7786	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\1:270C"}
278	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7886	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:1201"}
279	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7781	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:1004"}
280	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7216	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:1001"}
281	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7026	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:270C"}
282	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7851	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:2201"}
283	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7066	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:120c"}
284	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7856	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:120b"}
285	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7246	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1405"}
286	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7286	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1200"}
287	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7211	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1201"}
288	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7411	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1004"}
289	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7546	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:1001"}
290	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7186	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:270C"}
291	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7866	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2201"}
292	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7096	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:120c"}
293	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7801	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:120b"}
294	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7416	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\2:2600"}
295	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7446	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\1:2600"}
296	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7941	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:2600"}
297	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7626	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:2001"}
298	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7331	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\3:2004"}
299	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7761	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2600"}
300	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7946	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2001"}
301	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7101	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2004"}
302	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7911	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2401"}
303	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7011	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2402"}
304	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_7251	{3}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\Internet Settings\\\\\\\\Zones\\\\\\\\4:2400"}
305	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0467	{1}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\Appx:BlockNonAdminUserInstall"}
306	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0891	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\Messaging:AllowMessageSync"}
307	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0081	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\StorageSense:AllowStorageSenseGlobal"}
308	2022-09-23 14:51:25.391127	2	windows10	Chinese	BL696_0141	{0}	0	{"Machine\\\\\\\\Software\\\\\\\\Policies\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\System:AllowCrossDeviceClipboard"}
\.


--
-- Data for Name: result; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.result (rid, "timestamp", utc, id, os, lang, server_ip, host_ip, rule_id, expected, actual, status) FROM stdin;
\.


--
-- Data for Name: statistics; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.statistics (sid, check_time, utc, host_ip, failed_list, pass_list) FROM stdin;
\.


--
-- Name: cid; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cid', 308, true);


--
-- Name: result_rid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.result_rid_seq', 0, true);


--
-- Name: statistics_sid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.statistics_sid_seq', 0, true);


--
-- Name: config config_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.config
    ADD CONSTRAINT config_pkey PRIMARY KEY (cid);


--
-- Name: result result_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.result
    ADD CONSTRAINT result_pkey PRIMARY KEY (rid);


--
-- Name: statistics statistics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.statistics
    ADD CONSTRAINT statistics_pkey PRIMARY KEY (sid);


--
-- PostgreSQL database dump complete
--

