ALTER TABLE config ALTER COLUMN cid SET default nextval('public.cid');
INSERT INTO config 
	(timestamp, id, os, lang, rule_id, data, type, param)
VALUES
(now(),	2,	'windows10',	'Chinese',	'BL696_1961',	'{1,1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\NetworkProvider\\\\HardenedPaths:RequireIntegrity","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\NetworkProvider\\\\HardenedPaths:RequireMutualAuthentication"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0956',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\Network Connections:NC_AllowNetBridge_NLA"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0375',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Microsoft\\\\wcmsvc\\\\wifinetworkmanager\\\\config:AutoConnectAllowedOEM"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0522',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\LanmanWorkstation:AllowInsecureGuestAuth"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0656',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows NT\\\\DNSClient:EnableMulticast"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0631',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Policies\\\\System\\\\Audit:ProcessCreationincludeCmdLine_Enabled"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0001',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\System:BlockDomainPicturePassword"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0236',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\System:AllowDomainPINLogon"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0116',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Power\\\\PowerSettings\\\\0e796bdb_100d_47d6_a2d5_f7d2daa51f51:DCSettingIndex"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0066',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Power\\\\PowerSettings\\\\0e796bdb_100d_47d6_a2d5_f7d2daa51f51:ACSettingIndex"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7520',	'{127}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\PassportForWork\\\\PINComplexity:MaximumPINLength"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7521',	'{8}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\PassportForWork\\\\PINComplexity:MinimumPINLength"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0284',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\W32time\\\\TimeProviders\\\\NtpClient:Enabled"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0621',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:CreateEncryptedOnlyTickets"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0691',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:LoggingEnabled"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0931',	'{1,1,0,1,1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:fAllowToGetHelp","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:fAllowFullControl","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:MaxTickertExpiry","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:MaxTickertExpiryUnits","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:fUseMailto"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0866',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Policies\\\\System\\\\CredSSP\\\\Parameters:AllowEncryptionOracle"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0759',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\AdvertisingInfo:DisabledByGroupPolicy"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1581',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\SQMClient\\\\Windows:CEIPEnable"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1231',	'{2}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Messenger\\\\Client:CEIP"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1196',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\Windows Error Reporting:Disabled"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0166',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\TabletPC:PreventHandwritingDataSharing"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0761',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\HandwritingErrorReports:PreventHandwritingErrorReports"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0391',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\InputPersonalization:AllowInputPersonalization"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1381',	'{1}',	0,	'{"User\\\\Software\\\\Policies\\\\Microsoft\\\\WindowsMediaPlayer:EnableScreenSaver"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1211',	'{1}',	0,	'{"User\\\\Software\\\\Policies\\\\Microsoft\\\\WindowsMediaPlayer:PreventCDDVDMetadataRetrieval"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1601',	'{1}',	0,	'{"User\\\\Software\\\\Policies\\\\Microsoft\\\\WindowsMediaPlayer:PreventCodecDownload"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1866',	'{1}',	0,	'{"User\\\\Software\\\\Policies\\\\Microsoft\\\\WindowsMediaPlayer:PreventMusicFileMetadataRetrieval"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0186',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\PreviewBuilds:AllowBuildPreview"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0602',	'{4}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\WindowsUpdate\\\\AU:AUOptions"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0721',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\WindowsUpdate:ManagePreviewBuilds"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1011',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\Explorer:NoAutoplayfornonVolume"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1041',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Policies\\\\Explorer:NoAutorun"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1891',	'{181}',	0,	'{"Machine\\\\SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Policies\\\\Explorer:NoDriveTypeAutoRun"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0556',	'{131072}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\EventLog\\\\Application:MaxSize"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0491',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\EventLog\\\\Application:Retention"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0671',	'{524288}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\EventLog\\\\Security:MaxSize"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0176',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\EventLog\\\\Security:Retention"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0681',	'{131072}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\EventLog\\\\System:MaxSize"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0651',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\EventLog\\\\System:Retention"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0376',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\EventLog\\\\Setup:Enabled"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0766',	'{131072}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\EventLog\\\\Setup:MaxSize"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0051',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\EventLog\\\\Setup:Retention"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0046',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\System:NolocalPasswordResetQuestions"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0277',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\MicrosoftAccount:DisableUserAuth"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0316',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Policies\\\\System:DisableAutomaticRestartSignOn"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1926',	'{0,1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\PassportForWork:DisablePostLogonProvisioning","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\PassportForWork:Enabled"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_8451',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\PassportForWork\\\\ExcludeSecurityDevices:TPM12"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_5551',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\WinBio\\\\Credential Provider:Domain Accounts"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_5557',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\PassportForWork:UserCertificateForOnPremAuth"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_9356',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\PassportForWork:EnablePinRecovery"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7642',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Biometrics\\\\FacialFeatures:EnhancedAntiSpoofing"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0739',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\HomeGroup:AllowInsecureGuestAuth"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0706',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:AuthenticationLevel"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0776',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:DisablePasswordSaving"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0836',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:fPromptForPassword"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0246',	'{2}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:SecurityLayer"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0511',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:UserAuthentication"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0666',	'{3}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:MinEncryptionLevel"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0156',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:fDenyTSConnections"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0911',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\WinRM\\\\Client:AllowBasic"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0841',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\WinRM\\\\Client:AllowUnencryptedTraffic"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0606',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\WinRM\\\\Service:AllowBasic"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0581',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\WinRM\\\\Service:AllowUnencryptedTraffic"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0736',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\GameDVR:AllowGameDVR"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0396',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:MorBehavior"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0331',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:DisableExternalDMAUnderLock"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0226',	'{1,Siemens AG}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:IdentificationField","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:IdentificationFieldString"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0971',	'{7,4,4}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:EncryptionMethodWithXtsFdv","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:EncryptionMethodWithXtsOs","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:EncryptionMethodWithXtsRdv"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1636',	'{0,0,0,0,0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:FDVActiveDirectoryBackup","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:FDVHideRecoveryPage","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:FDVManageDRA","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:FDVRecovery","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:FDVRequireActiveDirectoryBackup"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1871',	'{0,0,0,0,0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:OSActiveDirectoryBackup","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:OSHideRecoveryPage","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:OSManageDRA","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:OSRecovery","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:OSRequireActiveDirectoryBackup"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1116',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:FDVEncryptionType"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1826',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:OSEncryptionType"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1366',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:OSEnablePreBootPinExceptionOnDECapableDevice"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1466',	'{8}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:MinimumPIN"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1371',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:OSEnablePrebootInputProtectorsOnSlates"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1981',	'{1,1,2,2,2,2}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:UseAdvancedStartup","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:EnableBDEWithNoTPM","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:UseTPM","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:UseTPMPIN","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:UseTPMKey","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:UseTPMKeyPIN"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1206',	'{0,0,0,0,0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:RDVActiveDirectoryBackup","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:RDVHideRecoveryPage","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:RDVManageDRA","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:RDVRecovery","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:RDVRequireActiveDirectoryBackup"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1101',	'{1,0,2,8}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:RDVPassphrase","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:RDVEnforcePassphrase","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:RDVPassphraseComplexity","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:RDVPassphraseLength"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1671',	'{1,1,1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:RDVConfigureBDE","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:RDVAllowBDE","Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:RDVDisableBDE"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1201',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\FVE:RDVEncryptionType"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0756',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\AppPrivacy:LetAppsActivateWithVoice"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0341',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\AppPrivacy:LetAppsActivateWithVoiceAboveLock"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1791',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\LocationAndSensors:DisableLocation"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1226',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\LocationAndSensors:DisableLocationScripting"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0689',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\AppPrivacy:LetAppsAccessAccountInfo"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0968',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\AppPrivacy:LetAppsGetDiagnosticInfo"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1651',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\DataCollection:AllowTelemetry"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1446',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\DataCollection:DoNotShowFeedbackNotifications"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1856',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\DataCollection:DisableTelemetryOptInSettingsUx"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1236',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\DataCollection:DisableTelemetryOptInChangeNotificatification"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0353',	'{2}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\AppPrivacy:LetAppsSyncWithDevices"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1291',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\Windows Search:DisableWebSearch"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1096',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\Windows Search:ConnectedSearchUseWeb"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1736',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\Windows Error Reporting:Disabled"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0261',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Policies\\\\TextInput:AllowLinguisticDataCollection"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0372',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\AppPrivacy:LetAppsAccessBackgroundSpatialPerception"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1181',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\WindowsMediaPlayer:GroupPrivacyAcceptance"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1661',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\WindowsMediaPlayer:DisableAutoUpdate"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1306',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\WindowsMediaPlayer:PreventLibrarySharing"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1391',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\PushToInstall:DisablePushToInstall"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0564',	'{1}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\CloudContent:DisableWindowsConsumerFeatures"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1841',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\Windows Search:AllowCortana"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1906',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\Windows Search:AllowCortanaAboveLock"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0526',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\System:PublishUserActivities"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0686',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\System:UploadUserActivities"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0796',	'{0}',	0,	'{"Machine\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\System:EnableMmx"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0711',	'{1,AllSigned}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\PowerShell:EnableScripts","Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\PowerShell:ExecutionPolicy"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0461',	null,	0,	'{"Xbox Live 网络服务"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0946',	null,	0,	'{"Xbox Live 游戏保存"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0416',	null,	0,	'{"Xbox Live 身份验证管理器"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0506',	null,	0,	'{"Xbox Accessory Management Service"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0521',	null,	0,	'{"Remote Access Auto Connection Manager"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0961',	null,	0,	'{"Microsoft iSCSI Initiator Service"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0846',	null,	0,	'{"LxssManager"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0386',	null,	0,	'{"Geolocation Service"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0056',	null,	0,	'{"Downloaded Maps Manager"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0936',	null,	0,	'{"蓝牙音频网关服务"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0636',	null,	0,	'{"蓝牙支持服务"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0086',	'{1}',	0,	'{"Machine\\\\System\\\\CurrentControlSet\\\\Control\\\\SCMConfig:EnableSvchostMitigationPolicy"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0655',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CloudContent:DisableSoftLanding"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1896',	'{1}',	0,	'{"User\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CloudContent:DisableWindowsSpotlightOnSettings"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1251',	'{1}',	0,	'{"User\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CloudContent:DisableWindowsSpotlightOnActionCenter"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1706',	'{1}',	0,	'{"User\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CloudContent:DisableWindowsSpotlightWindowsWelcomeExperience"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1156',	'{1}',	0,	'{"User\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CloudContent:DisableWindowsSpotlightFeatures"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1546',	'{1}',	0,	'{"User\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CloudContent:DisableTailoredExperiencesWithDiagnosticData"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1711',	'{1}',	0,	'{"User\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CloudContent:DisableThirdPartySuggestions"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1066',	'{2}',	0,	'{"User\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CloudContent:ConfigureWindowsSpotlight"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0951',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\PushNotifications:NoCloudApplicationNotification"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0611',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\System:DisableLockScreenAppNotifications"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0303',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\Connect:AllowProjectionToPC"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1941',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\WCN\\\\UI:DisableWcnUi"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1036',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\WCN\\\\Registrars:DisableInBand802DOT11Registrar"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0181',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\System:EnableActivityFeed"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0441',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\SecondaryAuthenticationFactor:AllowSecondaryAuthenticationDevice"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0194',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\System:EnableCdp"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1831',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\FVE:RDVHardwareEncryption"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1416',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\FVE:OSHardwareEncryption"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1971',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\FVE:FDVHardwareEncryption"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0819',	'{1}',	0,	'{"User\\\\Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Policies\\\\Explorer:NoRecycleFiles"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1341',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:fAllowUnsolicited"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1611',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows NT\\\\Terminal Services:fAllowToGetHelp"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1576',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CredentialsDelegation:AllowSavedCredentialsWhenNTLMOnly"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1596',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CredentialsDelegation:AllowSavedCredentials"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1491',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CredentialsDelegation:AllowSavedCredentials"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1696',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CredentialsDelegation:AllowFreshCredentialsWhenNTLMOnly"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1481',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CredentialsDelegation:AllowDefCredentialsWhenNTLMOnly"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1966',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CredentialsDelegation:AllowDefaultCredentials"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1526',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CredentialsDelegation:RestrictedRemoteAdministration"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1266',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CredentialsDelegation:AllowProtectedCreds"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1821',	'{1}',	0,	'{"Machine\\\\System\\\\CurrentControlSet\\\\Policies\\\\EarlyLaunch:DriverLoadPolicy"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1026',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\OneDrive:DisableFileSync"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0701',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\PassportForWork:Enabled"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_6453',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Spynet:DisableBlockAtFirstSeen"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7345',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Remediation:Scan_ScheduleDay"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_4652',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Real_Time Protection:LocalSettingOverrideDisableOnAccessProtection"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_4653',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Real_Time Protection:LocalSettingOverrideRealtimeScanDirection"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_2096',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Real_Time Protection:LocalSettingOverrideDisableRealtimeMonitoring"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_2034',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Real_Time Protection:LocalSettingOverrideDisableBehaviorMonitoring"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_5871',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Signature Updates:UpdateOnStartUp"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_2754',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Signature Updates:DisableUpdateOnStartupWithoutEngine"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_6483',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Scan:DisablePackedExeScanning"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_6444',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Scan:DisableHeuristics"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_6476',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\NIS:DisableProtocolRecognition"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_5456',	'{2}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\MpEngine:MpCloudBlockLevel"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_3987',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Real_Time Protection:DisableScanOnRealtimeEnable"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_6489',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Real_Time Protection:DisableRawWriteNotification"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_3934',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Real_Time Protection:DisableOnAccessProtection"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_3958',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Real_Time Protection:RealtimeScanDirection"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_4876',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Real_Time Protection:LocalSettingOverrideDisableIOAVProtection"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_4754',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Spynet:LocalSettingOverrideSpynetReporting"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_3654',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Real_Time Protection:DisableRealtimeMonitoring"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_4537',	'{2}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender:PUAProtection"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0486',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender Security Center\\\\App and Browser protection:DisallowExploitProtectionOverride"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_1421',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\System:EnableSmartScreen"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0306',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\DriverInstall\\\\Restrictions:AllowUserDeviceClasses"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0136',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Windows Defender Exploit Guard\\\\Network Protection:EnableNetworkProtection"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0616',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Scan:CheckForSignaturesBeforeRunningScan"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0696',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Signature Updates:SignatureUpdateInterval"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0531',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Scan:DisableEmailScanning"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0426',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Scan:DisableRemovableDriveScanning"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0746',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Scan:DisableArchiveScanning"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0771',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Real_Time Protection:DisableBehaviorMonitoring"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0541',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Real_Time Protection:DisableIOAVProtection"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0076',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\Reporting:DisableGenericRePorts"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0981',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows Defender:DisableAntiSpyware"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7896',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\1:1800"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7931',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:1607"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7556',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:1804"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7966',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:160A"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7561',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:2708"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7961',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:2709"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7266',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:2104"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7276',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:1800"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7356',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:1406"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7776',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1806"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7016',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1607"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7701',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1804"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7971',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:160A"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7351',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2708"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7381',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2709"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7951',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2104"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7926',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1608"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7091',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1800"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7676',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1407"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7751',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2300"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7261',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1406"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7136',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer\\\\Feeds:AllowBasicAuthInClear"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7496',	'{65536}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:1A00"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7876',	'{196608}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1A00"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7206',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:2500"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7156',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2500"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7006',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:1A04"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7296',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:1609"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7986',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1601"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7316',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1601"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7916',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1609"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7271',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings:WarnOnBadCertRecving"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7196',	'{2688}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings:SecureProtocols"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7041',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:1809"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7151',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1809"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7921',	'{2,1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\SettingSync:DisableCredentialsSettingSync","Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\SettingSync:DisableCredentialsSettingSyncUserOverride"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7111',	'{2,1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\SettingSync:DisableWebBrowserSettingSync","Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\SettingSync:DisableWebBrowserSettingSyncUserOverride"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7636',	'{1}',	0,	'{"User\\\\Software\\\\Policies\\\\Microsoft\\\\IEAK:NoAutomaticSignup"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7471',	'{no}',	0,	'{"User\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer\\\\Main:FormSuggest Passwords"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7161',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer\\\\Security:DisableSecuritySettingsCheck"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7461',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer\\\\PhishingFilter:EnabledV8"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7541',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer\\\\Main:DisableFirstRunCustomize"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7361',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer\\\\PhishingFilter:EnabledV9"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7231',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\2:2301"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7721',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\1:2301"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7086',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:2301"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7906',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2301"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7346',	'{yes}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer\\\\Main:NoReportSiteProblems"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7956',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer\\\\Suggested Sites:Enabled"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7871',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer\\\\Restrictions:NoCrashDetection"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7126',	'{2}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer\\\\Recovery:AutoRecover"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7191',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer\\\\SQM:DisableCustomerImprovementProgram"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7596',	'{1}',	0,	'{"User\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer\\\\Restrictions:NoHelpItemSendFeedback"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7121',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer:AllowServicePoweredQSA"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7726',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer\\\\FlipAhead:Enabled"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7766',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer\\\\Activities:NoActivities"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7426',	'{no}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Internet Explorer\\\\Main:Enable Browser Extensions"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7326',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\2:1409"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7526',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\1:1409"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7651',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:1409"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7616',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:2105"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7021',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:2103"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7631',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:2102"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7576',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:1206"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7976',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:1407"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7591',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:140C"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7806',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1409"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7731',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1402"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7571',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2105"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7771',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2103"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7981',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2102"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7051',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1206"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7831',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1407"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7816',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:140C"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7581',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1400"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7481',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:2200"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7536',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2200"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7586',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1604"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7146',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1803"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7641',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\2:120A"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7306',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\1:120A"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7501',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\1:1209"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7036',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:120A"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7681',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:1209"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7226',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:120A"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7566',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1209"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7301',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2000"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7366',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\2:270C"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7881',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\1:1201"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7371',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\1:1004"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7786',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\1:270C"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7886',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:1201"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7781',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:1004"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7216',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:1001"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7026',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:270C"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7851',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:2201"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7066',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:120c"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7856',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:120b"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7246',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1405"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7286',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1200"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7211',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1201"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7411',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1004"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7546',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:1001"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7186',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:270C"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7866',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2201"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7096',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:120c"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7801',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:120b"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7416',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\2:2600"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7446',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\1:2600"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7941',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:2600"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7626',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:2001"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7331',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\3:2004"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7761',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2600"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7946',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2001"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7101',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2004"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7911',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2401"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7011',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2402"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_7251',	'{3}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Internet Settings\\\\Zones\\\\4:2400"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0467',	'{1}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\Appx:BlockNonAdminUserInstall"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0891',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\Messaging:AllowMessageSync"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0081',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\StorageSense:AllowStorageSenseGlobal"}'),
(now(),	2,	'windows10',	'Chinese',	'BL696_0141',	'{0}',	0,	'{"Machine\\\\Software\\\\Policies\\\\Microsoft\\\\Windows\\\\System:AllowCrossDeviceClipboard"}');